config/urls.py
from users.views import account_signup_view, account_login_view
from django.contrib import admin                                                
from django.contrib.auth import views as auth_views                             
from django.urls import path, include                                           
from django.conf.urls.static import static                                      
from django.conf import settings                                                


urlpatterns = [                                             
    path('admin/', admin.site.urls),                 
    path('accounts/login/', view=account_login_view),
    path("accounts/signup/", view=account_signup_view),                                                                                                                 
    path('accounts/', include('allauth.urls')),                 
    path('users/', include('users.urls')), 
    path('', include('home.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),                                                                     
         name='password_reset'),                                                
    path('password-reset/done/',                                                
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),                                           
    path('password-reset-confirm/<uidb64>/<token>/',                            
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),                                                                     
         name='password_reset_confirm'),                                        
    path('password-reset-complete/',                                            
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),                                                                     
         name='password_reset_complete'),                                       
]                                                                               
                                                                                
if settings.DEBUG:                                                              
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home_view 

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

home_view = HomeView.as_view()

templates/base.html
<!DOCTYPE html>
{% load bootstrap5 %}
{% load static %}
<html lang='en-us'>
<head>
    <meta charset='utf-8' />
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no' />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{{ user.first_name|title }} | {% block title %}{% endblock title %}</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-th-lt">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            <a class="nav-link" href="{% url 'user_account' %}">Account</a>
            {% else %}
               <a class="nav-link" href="{% url 'account_login' %}">Login</a>
               <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
</header>
<main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }} box-sh">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}

          {% block content %}{% endblock content %}

        </div>
        <div class="col-md-4">
          {% block sidebar %}
          {% endblock sidebar %}
        </div>
      </div>
  </main>
	<script src="{% static "js/script.js" %}"></script>
</body>
</html>    

templates/home.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block title %}Home{% endblock title %}
{% block content %}
    <div class="container">
        <h1 class="mt-2">Home</h1>
    </div>
{% endblock content %}